# Generated by Django 5.0.4 on 2024-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('transporte', models.TimeField(max_length=20)),
                ('horario', models.TimeField()),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
