# Generated by Django 5.0.4 on 2024-04-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='transporte',
            field=models.CharField(max_length=20),
        ),
    ]
