# Generated by Django 5.0.4 on 2024-04-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_informacion_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='transporte',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Taxi', 'Taxi')], max_length=20),
        ),
    ]
