# Generated by Django 5.0.4 on 2024-04-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_alter_informacion_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='transporte',
            field=models.CharField(choices=[('Tren', 'Tren'), ('Corredor', 'Corredor'), ('Metropolitano', 'Metropolitano')], max_length=20),
        ),
    ]
